import { expect, test } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'
import path from 'node:path'
import { readFile } from 'node:fs/promises'

const profileText = `Alex Kim\nBackend Engineer\n5 years of software engineering experience.\nI build payment APIs with Python, TypeScript, React, Node.js, PostgreSQL and AWS.\nDO_NOT_PERSIST_RAW_RESUME alice-private@example.test`

test('3D map, region selection, city panel and 2D view stay connected', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  await expect(page.locator('.earth-canvas')).toHaveClass(/is-ready/)
  await expect(page.locator('.globe-pin').first()).toBeVisible()
  await expect(page.locator('.city-row')).toHaveCount(22)
  await page.getByRole('button', { name: /^런던, 추천 회사 \d+곳 보기$/ }).click()
  await expect(page.locator('.city-hero-caption h2')).toContainText('런던')
  await expect(page.locator('.company-card').first()).toBeVisible()
  await page.getByRole('button', { name: '모든 도시', exact: true }).click()
  await page.getByRole('button', { name: '유럽', exact: true }).click()
  await expect(page.locator('.city-row')).toHaveCount(9)
  await page.getByRole('button', { name: '2D 지도', exact: true }).click()
  await expect(page.locator('.flat-map svg')).toBeVisible()
  await expect(page.locator('.flat-marker').first()).toBeVisible()
  await page.getByRole('button', { name: '지도 확대', exact: true }).click()
  await page.getByLabel('도시, 회사 또는 포지션 검색').fill('존재하지않는회사')
  await expect(page.getByRole('heading', { name: '조건에 맞는 도시가 아직 없어요' })).toBeVisible()
  await expect(page.locator('.flat-marker')).toHaveCount(0)
  await page.getByRole('button', { name: '검색 조건 초기화', exact: true }).click()
  await expect(page.locator('.city-row')).toHaveCount(22)
  expect(errors).toEqual([])
})

test('profile text is parsed locally, reviewed and persisted without the raw resume', async ({ page }) => {
  const uploads: string[] = []
  page.on('request', request => { if (['POST', 'PUT', 'PATCH'].includes(request.method())) uploads.push(request.url()) })
  await page.goto('/')
  await page.getByRole('button', { name: '내 프로필 편집', exact: true }).click()
  await page.getByRole('button', { name: '텍스트', exact: true }).click()
  await page.getByLabel('경력 요약', { exact: true }).fill(profileText)
  await page.getByRole('button', { name: '경력에서 가능성 찾기', exact: true }).click()
  await expect(page.getByLabel('개발 경력', { exact: true })).toHaveValue('5')
  await expect(page.getByLabel('이름 또는 별명')).toHaveValue('Alex Kim')
  await page.getByLabel('희망 직무', { exact: true }).selectOption('backend')
  await page.getByLabel('비자 지원', { exact: true }).selectOption('yes')
  await page.getByRole('button', { name: '내 기회 지도 만들기', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.getByLabel('직무 필터')).toHaveValue('backend')
  await expect(page.getByLabel('비자 지원 필터')).toHaveValue('yes')
  const storage = await page.evaluate(() => Object.values(localStorage).join('\n'))
  expect(storage).not.toContain('DO_NOT_PERSIST_RAW_RESUME')
  expect(storage).not.toContain('alice-private@example.test')
  await page.reload()
  await expect(page.getByLabel('직무 필터')).toHaveValue('backend')
  await expect(page.getByLabel('비자 지원 필터')).toHaveValue('yes')
  await page.getByRole('button', { name: '내 프로필 편집', exact: true }).click()
  await page.getByRole('button', { name: '저장된 프로필 삭제 · 샘플로 돌아가기' }).click()
  expect(await page.evaluate(() => localStorage.getItem('orbit.v1.profile'))).toBeNull()
  await expect(page.locator('.sample-profile-card')).toBeVisible()
  expect(uploads).toEqual([])
})

test('zooming separates city clusters, and context loss switches to a usable 2D map', async ({ page }) => {
  await page.goto('/')
  await expect(page.locator('.earth-canvas')).toHaveClass(/is-ready/)
  await page.locator('.globe-pin.is-cluster').filter({ hasText: '런던' }).click()
  await page.getByRole('button', { name: '지도 확대', exact: true }).click()
  await page.getByRole('button', { name: '지도 확대', exact: true }).click()
  const london = page.locator('.globe-pin:not(.is-cluster)').filter({ hasText: '런던' })
  await expect(london).toBeVisible()
  await london.click()
  await expect(page.locator('.city-hero-caption h2')).toContainText('런던')
  await page.locator('.earth-canvas canvas').dispatchEvent('webglcontextlost')
  await expect(page.locator('.flat-map svg')).toBeVisible()
  await expect(page.locator('.company-card').first()).toBeVisible()
})

for (const extension of ['pdf', 'docx'] as const) {
  test(`${extension.toUpperCase()} resume is read in the browser`, async ({ page }) => {
    await page.goto('/')
    await page.getByRole('button', { name: '내 프로필 편집', exact: true }).click()
    await page.getByLabel('이력서 파일 선택').setInputFiles(path.resolve(`tests/fixtures/resume.${extension}`))
    await expect(page.getByText(`resume.${extension}`, { exact: true })).toBeVisible()
    await expect(page.getByLabel('읽어온 경력 · 필요한 부분을 수정하세요')).toHaveValue(/Python/)
    await page.getByRole('button', { name: '경력에서 가능성 찾기', exact: true }).click()
    await expect(page.getByLabel('개발 경력', { exact: true })).toHaveValue('5')
    await expect(page.getByRole('button', { name: 'Python 삭제', exact: true })).toBeVisible()
    await expect(page.locator('.form-error')).toHaveCount(0)
  })
}

test('Korean PDF text and names survive extraction', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: '내 프로필 편집', exact: true }).click()
  await page.getByLabel('이력서 파일 선택').setInputFiles(path.resolve('tests/fixtures/resume-ko.pdf'))
  await expect(page.getByLabel('읽어온 경력 · 필요한 부분을 수정하세요')).toHaveValue(/김민준/)
  await page.getByRole('button', { name: '경력에서 가능성 찾기', exact: true }).click()
  await expect(page.getByLabel('이름 또는 별명')).toHaveValue('김민준')
  await expect(page.getByLabel('개발 경력', { exact: true })).toHaveValue('5')
})

test('saved opportunities preserve notes and status, export CSV and support undo', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: /^런던, 추천 회사 \d+곳 보기$/ }).click()
  await page.locator('.mini-job-title').first().click()
  await page.getByRole('button', { name: '기회 저장', exact: true }).click()
  await page.getByLabel('이 기회에 대한 나의 메모').fill('다음 주 포트폴리오를 준비해서 지원하기')
  await page.getByRole('button', { name: '지원 완료로 표시', exact: true }).click()
  await page.getByRole('button', { name: '닫기', exact: true }).click()
  await page.getByRole('navigation', { name: '주요 메뉴' }).getByRole('button', { name: /저장한 기회/ }).click()
  await expect(page.locator('.saved-card')).toHaveCount(1)
  await expect(page.locator('.saved-note-preview')).toContainText('다음 주 포트폴리오')
  await page.reload()
  await expect(page.locator('.saved-status')).toHaveText('지원 완료')
  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: 'CSV 내보내기', exact: true }).click()
  const download = await downloadPromise
  const csv = await readFile((await download.path())!, 'utf8')
  expect(csv).toContain('다음 주 포트폴리오를 준비해서 지원하기')
  expect(csv).toContain('지원 완료')
  expect(csv).toContain('샘플')
  await page.getByRole('button', { name: 'Linear 저장 취소', exact: true }).click()
  await expect(page.locator('.saved-card')).toHaveCount(0)
  await page.getByRole('button', { name: '실행 취소', exact: true }).click()
  await expect(page.locator('.saved-card')).toHaveCount(1)
  await expect(page.locator('.saved-status')).toHaveText('지원 완료')
})

test('city comparison is limited to three cities and survives navigation', async ({ page }) => {
  await page.goto('/')
  for (const city of ['런던', '베를린', '샌프란시스코']) {
    await page.getByRole('button', { name: `${city} 비교에 추가`, exact: true }).click()
  }
  await page.getByRole('button', { name: '뉴욕 비교에 추가', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('최대 3개')
  await page.getByRole('navigation', { name: '주요 메뉴' }).getByRole('button', { name: /도시 비교/ }).click()
  await expect(page.locator('.comparison-city')).toHaveCount(3)
  await expect(page.locator('.comparison-city-name')).toContainText(['런던', '베를린', '샌프란시스코'])
  await page.reload()
  await expect(page.locator('.comparison-city')).toHaveCount(3)
  await page.getByRole('button', { name: '런던 비교에서 제거', exact: true }).click()
  await page.getByLabel('다른 도시 추가', { exact: true }).selectOption('amsterdam')
  await expect(page.locator('.comparison-city-name')).toContainText(['베를린', '샌프란시스코', '암스테르담'])
  const accessibility = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze()
  expect(accessibility.violations).toEqual([])
  await page.getByRole('button', { name: '비교 비우기', exact: true }).click()
  await expect(page.locator('.comparison-city')).toHaveCount(0)
})

test('a failed public feed never relabels sample data as real jobs', async ({ page }) => {
  await page.route('**/api/catalog?source=greenhouse*', route => route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ error: '게시판 연결을 확인해 주세요.' }) }))
  await page.goto('/')
  await page.getByRole('button', { name: '샘플 탐색', exact: true }).click()
  await page.getByRole('button', { name: /공개 채용공고/ }).click()
  await expect(page.getByRole('alert')).toContainText('게시판 연결을 확인해 주세요.')
  await expect(page.getByRole('button', { name: /샘플로 탐색/ })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: '닫기', exact: true }).click()
  await expect(page.getByRole('button', { name: '샘플 탐색', exact: true })).toBeVisible()
  await expect(page.locator('.city-row')).toHaveCount(22)
})

test('explore and profile forms pass WCAG A/AA checks and keyboard focus returns', async ({ page }) => {
  await page.goto('/')
  const explore = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze()
  expect(explore.violations).toEqual([])
  const trigger = page.getByRole('button', { name: '내 프로필 편집', exact: true })
  await trigger.click()
  const profile = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze()
  expect(profile.violations).toEqual([])
  await page.keyboard.press('Escape')
  await expect(trigger).toBeFocused()
  await page.keyboard.press('Meta+k')
  await expect(page.getByLabel('도시, 회사 또는 포지션 검색')).toBeFocused()
  await page.getByRole('button', { name: /^런던, 추천 회사 \d+곳 보기$/ }).click()
  await page.locator('.mini-job-title').first().click()
  const job = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze()
  expect(job.violations).toEqual([])
})

test.describe('mobile', () => {
  test.use({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true })
  test('touch-sized layout connects the globe to the city list without horizontal overflow', async ({ page }) => {
    await page.goto('/')
    await expect(page.locator('.earth-canvas')).toHaveClass(/is-ready/)
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.getByRole('button', { name: '도시 목록 보기', exact: true }).click()
    await expect(page.getByRole('button', { name: /^런던, 추천 회사 \d+곳 보기$/ })).toBeInViewport()
    await page.getByRole('button', { name: /^런던, 추천 회사 \d+곳 보기$/ }).click()
    await expect(page.locator('.city-hero-caption h2')).toBeInViewport()
    await page.locator('.mini-job-title').first().click()
    await expect(page.getByRole('dialog')).toBeVisible()
    const bounds = await page.getByRole('dialog').boundingBox()
    expect(bounds!.width).toBeLessThanOrEqual(390)
    await page.getByRole('button', { name: '기회 저장', exact: true }).click()
    await expect(page.getByRole('button', { name: '저장됨', exact: true })).toBeVisible()
  })
})
