import type { City } from './types'

export const CITIES: City[] = [
  { id: 'san-francisco', name: '샌프란시스코', en: 'San Francisco', country: '미국', countryCode: 'US', region: 'americas', lat: 37.7749, lng: -122.4194, timezone: 'America/Los_Angeles', description: '아이디어가 제품이 되는 곳. AI와 개발자 도구부터 차세대 스타트업까지 만나보세요.', image: 'san-francisco' },
  { id: 'new-york', name: '뉴욕', en: 'New York', country: '미국', countryCode: 'US', region: 'americas', lat: 40.7128, lng: -74.006, timezone: 'America/New_York', description: '금융과 기술, 크리에이티브가 교차하는 도시. 다양한 산업의 엔지니어링 팀을 탐색하세요.', image: 'new-york' },
  { id: 'seattle', name: '시애틀', en: 'Seattle', country: '미국', countryCode: 'US', region: 'americas', lat: 47.6062, lng: -122.3321, timezone: 'America/Los_Angeles', description: '클라우드와 인프라 기술이 성장하는 태평양 연안의 테크 허브.', image: 'seattle' },
  { id: 'austin', name: '오스틴', en: 'Austin', country: '미국', countryCode: 'US', region: 'americas', lat: 30.2672, lng: -97.7431, timezone: 'America/Chicago', description: '새로운 팀과 기술이 모이는 텍사스의 엔지니어링 커뮤니티.' },
  { id: 'boston', name: '보스턴', en: 'Boston', country: '미국', countryCode: 'US', region: 'americas', lat: 42.3601, lng: -71.0589, timezone: 'America/New_York', description: '연구와 산업을 잇는 도시. 데이터와 소프트웨어의 접점을 찾아보세요.' },
  { id: 'atlanta', name: '애틀랜타', en: 'Atlanta', country: '미국', countryCode: 'US', region: 'americas', lat: 33.749, lng: -84.388, timezone: 'America/New_York', description: '핀테크와 물류, 기업용 소프트웨어 팀이 모이는 미국 남동부의 기술 허브.' },
  { id: 'los-angeles', name: '로스앤젤레스', en: 'Los Angeles', country: '미국', countryCode: 'US', region: 'americas', lat: 34.0522, lng: -118.2437, timezone: 'America/Los_Angeles', description: '게임과 미디어, 모빌리티의 엔지니어링을 만나보세요. 산타모니카·컬버시티를 포함한 LA 권역의 공고를 표시합니다.' },
  { id: 'portland', name: '포틀랜드', en: 'Portland', country: '미국', countryCode: 'US', region: 'americas', lat: 45.5152, lng: -122.6784, timezone: 'America/Los_Angeles', description: '오리건의 소프트웨어와 반도체, 데이터 팀을 탐색하세요. 비버턴·힐스버러·타이거드를 포함한 권역입니다.' },
  { id: 'toronto', name: '토론토', en: 'Toronto', country: '캐나다', countryCode: 'CA', region: 'americas', lat: 43.6532, lng: -79.3832, timezone: 'America/Toronto', description: '다양한 배경의 인재가 함께하는 캐나다의 기술 중심지.', image: 'toronto' },
  { id: 'vancouver', name: '밴쿠버', en: 'Vancouver', country: '캐나다', countryCode: 'CA', region: 'americas', lat: 49.2827, lng: -123.1207, timezone: 'America/Vancouver', description: '태평양과 산 사이, 글로벌 기술 팀과 연결되는 도시.' },
  { id: 'london', name: '런던', en: 'London', country: '영국', countryCode: 'GB', region: 'europe', lat: 51.5074, lng: -0.1278, timezone: 'Europe/London', description: '세계의 팀이 연결되는 도시. 핀테크부터 AI까지, 커리어의 다음 가능성을 발견하세요.', image: 'london' },
  { id: 'berlin', name: '베를린', en: 'Berlin', country: '독일', countryCode: 'DE', region: 'europe', lat: 52.52, lng: 13.405, timezone: 'Europe/Berlin', description: '새로운 시도에 열려 있는 도시. 제품 중심의 스타트업과 글로벌 엔지니어링 팀을 만나보세요.', image: 'berlin' },
  { id: 'amsterdam', name: '암스테르담', en: 'Amsterdam', country: '네덜란드', countryCode: 'NL', region: 'europe', lat: 52.3676, lng: 4.9041, timezone: 'Europe/Amsterdam', description: '국제적인 팀과 탄탄한 제품 문화. 유럽의 연결점에서 새로운 일을 시작하세요.', image: 'amsterdam' },
  { id: 'paris', name: '파리', en: 'Paris', country: '프랑스', countryCode: 'FR', region: 'europe', lat: 48.8566, lng: 2.3522, timezone: 'Europe/Paris', description: 'AI 연구와 제품 개발이 만나는 유럽의 기술 생태계.', image: 'paris' },
  { id: 'dublin', name: '더블린', en: 'Dublin', country: '아일랜드', countryCode: 'IE', region: 'europe', lat: 53.3498, lng: -6.2603, timezone: 'Europe/Dublin', description: '글로벌 기업의 유럽 팀과 함께 성장할 기회를 찾아보세요.' },
  { id: 'stockholm', name: '스톡홀름', en: 'Stockholm', country: '스웨덴', countryCode: 'SE', region: 'europe', lat: 59.3293, lng: 18.0686, timezone: 'Europe/Stockholm', description: '음악, 결제, 디지털 경험을 만드는 북유럽의 제품 중심 도시.' },
  { id: 'zurich', name: '취리히', en: 'Zurich', country: '스위스', countryCode: 'CH', region: 'europe', lat: 47.3769, lng: 8.5417, timezone: 'Europe/Zurich', description: '정교한 기술과 연구가 만나는 도시. 인프라와 데이터 분야를 살펴보세요.' },
  { id: 'barcelona', name: '바르셀로나', en: 'Barcelona', country: '스페인', countryCode: 'ES', region: 'europe', lat: 41.3851, lng: 2.1734, timezone: 'Europe/Madrid', description: '지중해의 일상 속, 국제적인 제품 팀이 모여드는 도시.' },
  { id: 'lisbon', name: '리스본', en: 'Lisbon', country: '포르투갈', countryCode: 'PT', region: 'europe', lat: 38.7223, lng: -9.1393, timezone: 'Europe/Lisbon', description: '대서양을 바라보며 세계의 팀과 연결되는 스타트업 커뮤니티.' },
  { id: 'singapore', name: '싱가포르', en: 'Singapore', country: '싱가포르', countryCode: 'SG', region: 'asia-pacific', lat: 1.3521, lng: 103.8198, timezone: 'Asia/Singapore', description: '동남아시아를 연결하는 기술과 비즈니스의 허브.', image: 'singapore' },
  { id: 'seoul', name: '서울', en: 'Seoul', country: '대한민국', countryCode: 'KR', region: 'asia-pacific', lat: 37.5665, lng: 126.978, timezone: 'Asia/Seoul', description: '빠른 제품 실험과 깊이 있는 기술. 익숙한 도시에서 새로운 팀을 발견하세요.', image: 'seoul' },
  { id: 'tokyo', name: '도쿄', en: 'Tokyo', country: '일본', countryCode: 'JP', region: 'asia-pacific', lat: 35.6762, lng: 139.6503, timezone: 'Asia/Tokyo', description: '오랜 기술 기반과 새로운 스타트업이 함께 만들어가는 가능성.', image: 'tokyo' },
  { id: 'sydney', name: '시드니', en: 'Sydney', country: '호주', countryCode: 'AU', region: 'asia-pacific', lat: -33.8688, lng: 151.2093, timezone: 'Australia/Sydney', description: '전 세계가 사용하는 제품을 만드는 호주의 크리에이티브 테크 허브.', image: 'sydney' },
  { id: 'melbourne', name: '멜버른', en: 'Melbourne', country: '호주', countryCode: 'AU', region: 'asia-pacific', lat: -37.8136, lng: 144.9631, timezone: 'Australia/Melbourne', description: '디자인과 엔지니어링, 다양한 관점이 함께하는 도시.' },
  { id: 'bengaluru', name: '벵갈루루', en: 'Bengaluru', country: '인도', countryCode: 'IN', region: 'asia-pacific', lat: 12.9716, lng: 77.5946, timezone: 'Asia/Kolkata', description: '대규모 시스템과 글로벌 제품을 개발하는 인도의 기술 중심지.' },
  { id: 'taipei', name: '타이베이', en: 'Taipei', country: '대만', countryCode: 'TW', region: 'asia-pacific', lat: 25.033, lng: 121.5654, timezone: 'Asia/Taipei', description: '반도체 생태계와 글로벌 소프트웨어 팀이 만나는 대만의 중심지. 신베이를 포함한 타이베이 권역을 탐색하세요.' },
  { id: 'hsinchu', name: '신주', en: 'Hsinchu', country: '대만', countryCode: 'TW', region: 'asia-pacific', lat: 24.8138, lng: 120.9675, timezone: 'Asia/Taipei', description: '반도체와 하드웨어, 임베디드 소프트웨어를 잇는 대만의 연구·개발 거점.' },
  { id: 'hong-kong', name: '홍콩', en: 'Hong Kong', country: '홍콩', countryCode: 'HK', region: 'asia-pacific', lat: 22.3193, lng: 114.1694, timezone: 'Asia/Hong_Kong', description: '금융과 물류, 글로벌 서비스의 소프트웨어 팀을 만나보세요. 홍콩섬과 카오룽의 공고를 함께 표시합니다.' },
  { id: 'bangkok', name: '방콕', en: 'Bangkok', country: '태국', countryCode: 'TH', region: 'asia-pacific', lat: 13.7563, lng: 100.5018, timezone: 'Asia/Bangkok', description: '여행과 커머스, 모빌리티 플랫폼을 만드는 동남아시아의 제품 개발 거점.' },
  { id: 'kuala-lumpur', name: '쿠알라룸푸르', en: 'Kuala Lumpur', country: '말레이시아', countryCode: 'MY', region: 'asia-pacific', lat: 3.139, lng: 101.6869, timezone: 'Asia/Kuala_Lumpur', description: '핀테크와 플랫폼, 글로벌 서비스 팀을 탐색하세요. 페탈링자야를 포함한 쿠알라룸푸르 권역의 공고를 표시합니다.' },
  { id: 'manila', name: '마닐라', en: 'Manila', country: '필리핀', countryCode: 'PH', region: 'asia-pacific', lat: 14.5995, lng: 120.9842, timezone: 'Asia/Manila', description: '금융과 디지털 서비스의 엔지니어링 팀을 찾아보세요. 마카티·타기그·케손시티·파시그·만달루용을 포함한 메트로 마닐라 권역입니다.' },
  { id: 'auckland', name: '오클랜드', en: 'Auckland', country: '뉴질랜드', countryCode: 'NZ', region: 'asia-pacific', lat: -36.8509, lng: 174.7645, timezone: 'Pacific/Auckland', description: '농업 기술부터 결제와 SaaS까지, 세계 시장을 향하는 뉴질랜드의 제품 팀을 만나보세요.' },
  { id: 'wellington', name: '웰링턴', en: 'Wellington', country: '뉴질랜드', countryCode: 'NZ', region: 'asia-pacific', lat: -41.2865, lng: 174.7762, timezone: 'Pacific/Auckland', description: '디지털 서비스와 게임, 창의적인 소프트웨어 팀이 함께하는 뉴질랜드의 수도.' },
  { id: 'christchurch', name: '크라이스트처치', en: 'Christchurch', country: '뉴질랜드', countryCode: 'NZ', region: 'asia-pacific', lat: -43.5321, lng: 172.6362, timezone: 'Pacific/Auckland', description: '산업 기술과 소프트웨어, 새로운 제품을 만드는 뉴질랜드 남섬의 기술 거점.' },
  { id: 'dubai', name: '두바이', en: 'Dubai', country: '아랍에미리트', countryCode: 'AE', region: 'middle-east', lat: 25.2048, lng: 55.2708, timezone: 'Asia/Dubai', description: '중동의 금융·물류·디지털 서비스를 연결하는 도시. 글로벌 제품과 플랫폼 팀을 탐색하세요.' },
]

export const CITY_BY_ID = new Map(CITIES.map(city => [city.id, city]))

export const LOCATION_ALIASES: Record<string, string[]> = {
  'san-francisco': ['san francisco', 'san francisco bay area', 'bay area', 'south san francisco'],
  'new-york': ['new york', 'new york city', 'nyc', 'manhattan', 'brooklyn'],
  seattle: ['seattle'],
  austin: ['austin'],
  boston: ['boston', 'cambridge, ma', 'cambridge, massachusetts'],
  atlanta: ['atlanta', '애틀랜타', '아틀란타'],
  'los-angeles': ['los angeles', 'santa monica', 'culver city', '로스앤젤레스', '로스엔젤레스', '산타모니카', '컬버시티'],
  portland: ['portland', 'beaverton', 'hillsboro', 'tigard', '포틀랜드', '비버턴', '힐스버러', '타이거드'],
  toronto: ['toronto'],
  vancouver: ['vancouver'],
  london: ['london'],
  berlin: ['berlin'],
  amsterdam: ['amsterdam'],
  paris: ['paris'],
  dublin: ['dublin'],
  stockholm: ['stockholm'],
  zurich: ['zurich', 'zürich'],
  barcelona: ['barcelona'],
  lisbon: ['lisbon', 'lisboa'],
  singapore: ['singapore'],
  seoul: ['seoul', '서울'],
  tokyo: ['tokyo', '東京'],
  sydney: ['sydney'],
  melbourne: ['melbourne'],
  bengaluru: ['bengaluru', 'bangalore'],
  taipei: ['taipei', 'new taipei', '台北', '臺北', '台北市', '臺北市', '新北', '新北市', '타이베이', '신베이'],
  hsinchu: ['hsinchu', 'hsin-chu', 'hsin chu', '新竹', '新竹市', '新竹縣', '新竹县', '신주'],
  'hong-kong': ['hong kong', 'hongkong', 'kowloon', 'kwun tong', 'quarry bay', '香港', '九龍', '九龙', '홍콩', '카오룽'],
  bangkok: ['bangkok', 'กรุงเทพมหานคร', 'กรุงเทพฯ', '방콕'],
  'kuala-lumpur': ['kuala lumpur', 'petaling jaya', '쿠알라룸푸르', '페탈링자야'],
  manila: ['manila', 'metro manila', 'makati', 'taguig', 'quezon city', 'pasig', 'mandaluyong', '마닐라', '마카티', '타기그'],
  auckland: ['auckland', 'tāmaki makaurau', 'tamaki makaurau', '오클랜드'],
  wellington: ['wellington', 'te whanganui-a-tara', '웰링턴'],
  christchurch: ['christchurch', 'ōtautahi', 'otautahi', '크라이스트처치'],
  dubai: ['dubai', 'dubaï', 'دبي', '두바이'],
}
