import type { Company, JobProvider } from './types'

export const COMPANIES: Company[] = [
  { id: 'stripe', name: 'Stripe', initials: 'S', color: '#a79aff', industry: '핀테크 · 결제 인프라', careerUrl: 'https://stripe.com/jobs', board: 'stripe' },
  { id: 'figma', name: 'Figma', initials: 'F', color: '#ff9c78', industry: '디자인 · 협업 도구', careerUrl: 'https://www.figma.com/careers/', board: 'figma' },
  { id: 'notion', name: 'Notion', initials: 'N', color: '#e6e8e6', industry: '생산성 · 협업', careerUrl: 'https://www.notion.com/careers', board: 'notion' },
  { id: 'linear', name: 'Linear', initials: 'L', color: '#a4a3ff', industry: '개발자 도구', careerUrl: 'https://linear.app/careers' },
  { id: 'vercel', name: 'Vercel', initials: '▲', color: '#f4f4f4', industry: '클라우드 · 개발자 도구', careerUrl: 'https://vercel.com/careers', board: 'vercel' },
  { id: 'cloudflare', name: 'Cloudflare', initials: 'C', color: '#ffa75a', industry: '인프라 · 보안', careerUrl: 'https://www.cloudflare.com/careers/', board: 'cloudflare' },
  { id: 'datadog', name: 'Datadog', initials: 'D', color: '#bb9dfb', industry: '클라우드 · 모니터링', careerUrl: 'https://careers.datadoghq.com/', board: 'datadog' },
  { id: 'mongodb', name: 'MongoDB', initials: 'M', color: '#84dba6', industry: '데이터베이스', careerUrl: 'https://www.mongodb.com/careers', board: 'mongodb' },
  { id: 'spotify', name: 'Spotify', initials: 'S', color: '#72df99', industry: '오디오 · 미디어', careerUrl: 'https://www.lifeatspotify.com/jobs' },
  { id: 'airbnb', name: 'Airbnb', initials: 'A', color: '#ff929b', industry: '여행 · 마켓플레이스', careerUrl: 'https://careers.airbnb.com/', board: 'airbnb' },
  { id: 'gitlab', name: 'GitLab', initials: 'G', color: '#fbb384', industry: '개발자 도구 · DevSecOps', careerUrl: 'https://about.gitlab.com/jobs/', board: 'gitlab' },
  { id: 'elastic', name: 'Elastic', initials: 'E', color: '#f7d878', industry: '검색 · 데이터 분석', careerUrl: 'https://www.elastic.co/careers', board: 'elastic' },
  { id: 'wise', name: 'Wise', initials: 'W', color: '#b3e582', industry: '핀테크 · 글로벌 송금', careerUrl: 'https://wise.jobs/' },
  { id: 'revolut', name: 'Revolut', initials: 'R', color: '#d7daff', industry: '핀테크 · 디지털 금융', careerUrl: 'https://www.revolut.com/careers/' },
  { id: 'adyen', name: 'Adyen', initials: 'A', color: '#77dfa1', industry: '핀테크 · 결제', careerUrl: 'https://careers.adyen.com/' },
  { id: 'shopify', name: 'Shopify', initials: 'S', color: '#b5db7a', industry: '커머스 · 플랫폼', careerUrl: 'https://www.shopify.com/careers' },
  { id: 'canva', name: 'Canva', initials: 'C', color: '#7fdde1', industry: '디자인 · 크리에이티브', careerUrl: 'https://www.lifeatcanva.com/en/jobs/' },
  { id: 'atlassian', name: 'Atlassian', initials: 'A', color: '#83b5ff', industry: '협업 · 개발자 도구', careerUrl: 'https://www.atlassian.com/company/careers' },
  { id: 'miro', name: 'Miro', initials: 'M', color: '#f5d874', industry: '협업 · 비주얼 워크스페이스', careerUrl: 'https://miro.com/careers/' },
  { id: 'n26', name: 'N26', initials: 'N', color: '#94cdc2', industry: '핀테크 · 모바일 뱅킹', careerUrl: 'https://n26.com/en-eu/careers' },
  { id: 'zalando', name: 'Zalando', initials: 'Z', color: '#f6aa75', industry: '커머스 · 패션 테크', careerUrl: 'https://jobs.zalando.com/en/' },
  { id: 'delivery-hero', name: 'Delivery Hero', initials: 'D', color: '#fc8794', industry: '커머스 · 배달 플랫폼', careerUrl: 'https://careers.deliveryhero.com/' },
  { id: 'deepl', name: 'DeepL', initials: 'D', color: '#a1c3e1', industry: 'AI · 언어 기술', careerUrl: 'https://www.deepl.com/en/careers' },
  { id: 'hugging-face', name: 'Hugging Face', initials: 'H', color: '#f3cf69', industry: 'AI · 오픈소스', careerUrl: 'https://huggingface.co/join-us' },
  { id: 'anthropic', name: 'Anthropic', initials: 'A', color: '#d9b79f', industry: 'AI · 연구', careerUrl: 'https://www.anthropic.com/careers', board: 'anthropic' },
  { id: 'toss', name: '토스', initials: 't', color: '#80aeff', industry: '핀테크 · 디지털 금융', careerUrl: 'https://toss.im/career/jobs' },
  { id: 'karrot', name: '당근', initials: 'K', color: '#ffb084', industry: '로컬 · 커뮤니티', careerUrl: 'https://about.daangn.com/jobs/' },
  { id: 'smartnews', name: 'SmartNews', initials: 'S', color: '#8fbded', industry: '미디어 · 추천 시스템', careerUrl: 'https://careers.smartnews.com/' },
  { id: 'grab', name: 'Grab', initials: 'G', color: '#91dc9e', industry: '모빌리티 · 플랫폼', careerUrl: 'https://www.grab.careers/en/' },
  { id: 'mercari', name: 'Mercari', initials: 'M', color: '#ffa3a6', industry: '커머스 · 마켓플레이스', careerUrl: 'https://careers.mercari.com/' },
  { id: 'snyk', name: 'Snyk', initials: 'S', color: '#b8a3e6', industry: '개발자 보안', careerUrl: 'https://snyk.io/careers/', board: 'snyk' },
  { id: 'intercom', name: 'Intercom', initials: 'I', color: '#91bafd', industry: 'AI · 고객 경험', careerUrl: 'https://www.intercom.com/careers', board: 'intercom' },
]

function publicCompany(id: string, provider: JobProvider, board: string): Company {
  const company = COMPANIES.find(item => item.id === id)
  if (!company) throw new Error(`Unknown configured company: ${id}`)
  return { ...company, provider, board }
}

// Public coverage is independent of the 32 hand-authored sample scenarios.
export const PUBLIC_COMPANIES: Company[] = [
  ...['stripe', 'figma', 'vercel', 'cloudflare', 'datadog', 'mongodb', 'airbnb', 'gitlab', 'anthropic', 'intercom']
    .map(id => publicCompany(id, 'greenhouse', id)),
  { id: 'asana', name: 'Asana', initials: 'A', color: '#f6a7aa', industry: '업무 관리 · 협업', careerUrl: 'https://asana.com/jobs', provider: 'greenhouse', board: 'asana' },
  publicCompany('linear', 'ashby', 'Linear'),
  publicCompany('deepl', 'ashby', 'DeepL'),
  { id: 'n8n', name: 'n8n', initials: 'n', color: '#f5a193', industry: '자동화 · 개발자 도구', careerUrl: 'https://n8n.io/careers/', provider: 'ashby', board: 'n8n' },
  { id: 'supabase', name: 'Supabase', initials: 'S', color: '#90deb8', industry: '데이터베이스 · 개발자 도구', careerUrl: 'https://supabase.com/careers', provider: 'ashby', board: 'supabase' },
  { id: 'mistral', name: 'Mistral AI', initials: 'M', color: '#f0ad7f', industry: 'AI · 언어 모델', careerUrl: 'https://mistral.ai/careers/', provider: 'ashby', board: 'mistral.ai' },
  { id: 'jane', name: 'Jane', initials: 'J', color: '#83d1c7', industry: '헬스케어 · 진료 관리', careerUrl: 'https://jane.app/careers', provider: 'ashby', board: 'jane' },
  publicCompany('spotify', 'lever', 'spotify'),
  { id: 'contentsquare', name: 'Contentsquare', initials: 'C', color: '#f5bd83', industry: '디지털 경험 · 제품 분석', careerUrl: 'https://contentsquare.com/careers/', provider: 'lever', board: 'contentsquare' },
  publicCompany('canva', 'smartrecruiters', 'Canva'),
  publicCompany('grab', 'smartrecruiters', 'Grab'),
  publicCompany('wise', 'smartrecruiters', 'Wise'),
  { id: 'moloco', name: 'Moloco', initials: 'M', color: '#e8b283', industry: 'AI · 광고 기술', careerUrl: 'https://www.moloco.com/company/careers', provider: 'greenhouse', board: 'moloco' },
  { id: 'sendbird', name: 'Delight.ai (Sendbird)', initials: 'D', color: '#b6d9a2', industry: 'AI · 고객 경험', careerUrl: 'https://delight.ai/careers', provider: 'greenhouse', board: 'sendbird' },
  { id: 'openai', name: 'OpenAI', initials: 'O', color: '#9dd9c2', industry: 'AI · 연구', careerUrl: 'https://openai.com/careers/', provider: 'ashby', board: 'openai' },
  publicCompany('notion', 'ashby', 'notion'),
  { id: 'reddit', name: 'Reddit', initials: 'R', color: '#ffad88', industry: '커뮤니티 · 소셜 플랫폼', careerUrl: 'https://redditinc.com/careers', provider: 'greenhouse', board: 'reddit' },
  { id: 'discord', name: 'Discord', initials: 'D', color: '#aaa9ff', industry: '커뮤니티 · 커뮤니케이션', careerUrl: 'https://discord.com/careers', provider: 'greenhouse', board: 'discord' },
  { id: 'coinbase', name: 'Coinbase', initials: 'C', color: '#91b4ff', industry: '핀테크 · 디지털 자산', careerUrl: 'https://www.coinbase.com/careers', provider: 'greenhouse', board: 'coinbase' },
  { id: 'dropbox', name: 'Dropbox', initials: 'D', color: '#8cc9fa', industry: '클라우드 · 협업', careerUrl: 'https://www.dropbox.jobs/', provider: 'greenhouse', board: 'dropbox' },
  { id: 'duolingo', name: 'Duolingo', initials: 'D', color: '#b1df7c', industry: '교육 · 언어 학습', careerUrl: 'https://careers.duolingo.com/', provider: 'greenhouse', board: 'duolingo' },
  { id: 'roblox', name: 'Roblox', initials: 'R', color: '#c4cbd9', industry: '게임 · 크리에이터 플랫폼', careerUrl: 'https://careers.roblox.com/', provider: 'greenhouse', board: 'roblox' },
  { id: 'spacex', name: 'SpaceX', initials: 'S', color: '#9fbdda', industry: '우주 · 위성 통신', careerUrl: 'https://www.spacex.com/careers/', provider: 'greenhouse', board: 'spacex' },
  { id: 'pinterest', name: 'Pinterest', initials: 'P', color: '#f5a1ae', industry: '검색 · 콘텐츠 플랫폼', careerUrl: 'https://www.pinterestcareers.com/', provider: 'greenhouse', board: 'pinterest' },
  { id: 'databricks', name: 'Databricks', initials: 'D', color: '#ffb192', industry: '데이터 · AI 플랫폼', careerUrl: 'https://www.databricks.com/company/careers', provider: 'greenhouse', board: 'databricks' },
  { id: 'robinhood', name: 'Robinhood', initials: 'R', color: '#b6df92', industry: '핀테크 · 투자 플랫폼', careerUrl: 'https://careers.robinhood.com/', provider: 'greenhouse', board: 'robinhood' },
  publicCompany('adyen', 'greenhouse', 'adyen'),
  { id: 'affirm', name: 'Affirm', initials: 'A', color: '#f5bd83', industry: '핀테크', careerUrl: 'https://www.affirm.com/careers', provider: 'greenhouse', board: 'affirm' },
  { id: 'automattic', name: 'Automattic', initials: 'A', color: '#83d1c7', industry: '오픈소스 · 소프트웨어', careerUrl: 'https://automattic.com/work-with-us/', provider: 'greenhouse', board: 'automatticcareers' },
  { id: 'brave', name: 'Brave', initials: 'B', color: '#f5bd83', industry: '프라이버시 · 보안', careerUrl: 'https://brave.com/careers/', provider: 'greenhouse', board: 'brave' },
  { id: 'brex', name: 'Brex', initials: 'B', color: '#bb9dfb', industry: '핀테크', careerUrl: 'https://www.brex.com/careers', provider: 'greenhouse', board: 'brex' },
  { id: 'canonical', name: 'Canonical', initials: 'C', color: '#83d1c7', industry: '오픈소스 · 소프트웨어', careerUrl: 'https://canonical.com/careers', provider: 'greenhouse', board: 'canonical' },
  { id: 'clickhouse', name: 'ClickHouse', initials: 'C', color: '#91bafd', industry: '데이터 · 클라우드', careerUrl: 'https://clickhouse.com/company/careers', provider: 'ashby', board: 'ClickHouse' },
  { id: 'cockroachlabs', name: 'Cockroach Labs', initials: 'CL', color: '#ffad88', industry: '데이터 · 클라우드', careerUrl: 'https://www.cockroachlabs.com/careers/', provider: 'greenhouse', board: 'cockroachlabs' },
  { id: 'cohere', name: 'Cohere', initials: 'C', color: '#f5bd83', industry: 'AI · 연구', careerUrl: 'https://cohere.com/careers', provider: 'ashby', board: 'cohere' },
  { id: 'confluent', name: 'Confluent', initials: 'C', color: '#83d1c7', industry: '데이터 · 클라우드', careerUrl: 'https://careers.confluent.io/', provider: 'ashby', board: 'confluent' },
  { id: 'coupang', name: 'Coupang', initials: 'C', color: '#bb9dfb', industry: '커머스 · 플랫폼', careerUrl: 'https://www.coupang.jobs/en/', provider: 'greenhouse', board: 'coupang' },
  { id: 'cursor', name: 'Cursor', initials: 'C', color: '#91bafd', industry: 'AI · 개발자 도구', careerUrl: 'https://www.cursor.com/careers', provider: 'ashby', board: 'cursor' },
  publicCompany('delivery-hero', 'smartrecruiters', 'DeliveryHero'),
  { id: 'digitalocean', name: 'DigitalOcean', initials: 'D', color: '#ffad88', industry: '클라우드 · 인프라', careerUrl: 'https://www.digitalocean.com/careers', provider: 'greenhouse', board: 'digitalocean98' },
  { id: 'docker', name: 'Docker', initials: 'D', color: '#b6d9a2', industry: '개발자 도구', careerUrl: 'https://www.docker.com/careers/', provider: 'ashby', board: 'docker' },
  publicCompany('elastic', 'greenhouse', 'elastic'),
  { id: 'elevenlabs', name: 'ElevenLabs', initials: 'E', color: '#bb9dfb', industry: 'AI · 음성 기술', careerUrl: 'https://elevenlabs.io/careers', provider: 'ashby', board: 'elevenlabs' },
  { id: 'epicgames', name: 'Epic Games', initials: 'EG', color: '#b6d9a2', industry: '게임 · 플랫폼', careerUrl: 'https://www.epicgames.com/site/en-US/careers', provider: 'greenhouse', board: 'epicgames' },
  { id: 'fivetran', name: 'Fivetran', initials: 'F', color: '#b6d9a2', industry: '데이터 · 클라우드', careerUrl: 'https://www.fivetran.com/careers', provider: 'greenhouse', board: 'fivetran' },
  { id: 'grafana', name: 'Grafana Labs', initials: 'GL', color: '#91bafd', industry: '클라우드 · 모니터링', careerUrl: 'https://grafana.com/careers/', provider: 'greenhouse', board: 'grafanalabs' },
  { id: 'kong', name: 'Kong', initials: 'K', color: '#bb9dfb', industry: '클라우드 · API 인프라', careerUrl: 'https://konghq.com/careers', provider: 'ashby', board: 'kong' },
  { id: 'lyft', name: 'Lyft', initials: 'L', color: '#91bafd', industry: '모빌리티 · 플랫폼', careerUrl: 'https://www.lyft.com/careers', provider: 'greenhouse', board: 'lyft' },
  publicCompany('miro', 'greenhouse', 'realtimeboardglobal'),
  { id: 'mozilla', name: 'Mozilla', initials: 'M', color: '#b6d9a2', industry: '오픈소스 · 소프트웨어', careerUrl: 'https://www.mozilla.org/en-US/careers/', provider: 'greenhouse', board: 'mozilla' },
  publicCompany('n26', 'greenhouse', 'n26'),
  { id: 'okta', name: 'Okta', initials: 'O', color: '#91bafd', industry: '보안 · 인증', careerUrl: 'https://www.okta.com/company/careers/', provider: 'greenhouse', board: 'okta' },
  { id: 'palantir', name: 'Palantir', initials: 'P', color: '#b6d9a2', industry: '데이터 · 클라우드', careerUrl: 'https://www.palantir.com/careers/', provider: 'lever', board: 'palantir' },
  { id: 'perplexity', name: 'Perplexity', initials: 'P', color: '#f5bd83', industry: 'AI · 검색', careerUrl: 'https://www.perplexity.ai/hub/careers', provider: 'ashby', board: 'perplexity' },
  { id: 'plaid', name: 'Plaid', initials: 'P', color: '#bb9dfb', industry: '핀테크 · 금융 인프라', careerUrl: 'https://plaid.com/careers/', provider: 'ashby', board: 'plaid' },
  { id: 'posthog', name: 'PostHog', initials: 'P', color: '#83d1c7', industry: '개발자 도구 · 제품 분석', careerUrl: 'https://posthog.com/careers', provider: 'ashby', board: 'posthog' },
  { id: 'proton', name: 'Proton', initials: 'P', color: '#b6d9a2', industry: '프라이버시 · 보안', careerUrl: 'https://proton.me/careers', provider: 'greenhouse', board: 'proton' },
  { id: 'ramp', name: 'Ramp', initials: 'R', color: '#83d1c7', industry: '핀테크', careerUrl: 'https://ramp.com/careers', provider: 'ashby', board: 'ramp' },
  { id: 'replit', name: 'Replit', initials: 'R', color: '#ffad88', industry: 'AI · 개발자 도구', careerUrl: 'https://replit.com/careers', provider: 'ashby', board: 'replit' },
  { id: 'riotgames', name: 'Riot Games', initials: 'RG', color: '#f5bd83', industry: '게임 · 플랫폼', careerUrl: 'https://www.riotgames.com/en/work-with-us', provider: 'greenhouse', board: 'riotgames' },
  { id: 'runway', name: 'Runway', initials: 'R', color: '#b6d9a2', industry: 'AI · 영상 기술', careerUrl: 'https://runwayml.com/careers', provider: 'ashby', board: 'runway-ml' },
  { id: 'scaleai', name: 'Scale AI', initials: 'SA', color: '#83d1c7', industry: 'AI · 연구', careerUrl: 'https://scale.com/careers', provider: 'greenhouse', board: 'scaleai' },
  { id: 'sentry', name: 'Sentry', initials: 'S', color: '#91bafd', industry: '개발자 도구', careerUrl: 'https://sentry.io/careers/', provider: 'ashby', board: 'sentry' },
  { id: 'servicenow', name: 'ServiceNow', initials: 'S', color: '#91bafd', industry: '기업용 소프트웨어', careerUrl: 'https://careers.servicenow.com/', provider: 'smartrecruiters', board: 'ServiceNow' },
  { id: 'snowflake', name: 'Snowflake', initials: 'S', color: '#f5bd83', industry: '데이터 · 클라우드', careerUrl: 'https://careers.snowflake.com/', provider: 'ashby', board: 'snowflake' },
  { id: 'temporal', name: 'Temporal', initials: 'T', color: '#ffad88', industry: '개발자 도구', careerUrl: 'https://temporal.io/careers', provider: 'ashby', board: 'temporal' },
  { id: 'togetherai', name: 'Together AI', initials: 'TA', color: '#91bafd', industry: 'AI · 연구', careerUrl: 'https://www.together.ai/careers', provider: 'greenhouse', board: 'togetherai' },
  { id: 'twilio', name: 'Twilio', initials: 'T', color: '#f5bd83', industry: '클라우드 · 인프라', careerUrl: 'https://www.twilio.com/en-us/company/jobs', provider: 'greenhouse', board: 'twilio' },
  { id: 'twitch', name: 'Twitch', initials: 'T', color: '#bb9dfb', industry: '게임 · 플랫폼', careerUrl: 'https://www.twitch.tv/jobs/', provider: 'greenhouse', board: 'twitch' },
  { id: 'waymo', name: 'Waymo', initials: 'W', color: '#83d1c7', industry: '자율주행 · 모빌리티', careerUrl: 'https://waymo.com/careers/', provider: 'greenhouse', board: 'waymo' },
  { id: 'wikimedia', name: 'Wikimedia Foundation', initials: 'WF', color: '#bb9dfb', industry: '오픈소스 · 소프트웨어', careerUrl: 'https://wikimediafoundation.org/about/jobs/', provider: 'greenhouse', board: 'wikimedia' },
  { id: 'xai', name: 'xAI (SpaceXAI)', initials: 'x', color: '#ffad88', industry: 'AI · 연구', careerUrl: 'https://x.ai/careers', provider: 'greenhouse', board: 'xai' },
  { id: 'zoox', name: 'Zoox', initials: 'Z', color: '#bb9dfb', industry: '자율주행 · 모빌리티', careerUrl: 'https://zoox.com/careers/', provider: 'lever', board: 'zoox' },
  { ...publicCompany('hugging-face', 'workable', 'huggingface'), careerUrl: 'https://huggingface.co/JOIN-US' },
  { ...publicCompany('smartnews', 'workable', 'smartnews'), careerUrl: 'https://careers.smartnews.com/en/' },
  { ...publicCompany('mercari', 'workable', 'mercari'), careerUrl: 'https://careers.mercari.com/jobs/' },
  // These are the company's listings on Himalayas, not its entire careers inventory.
  { id: 'microsoft', name: 'Microsoft', initials: 'M', color: '#91bafd', industry: '클라우드 · 소프트웨어', careerUrl: 'https://careers.microsoft.com/v2/global/en/home.html', provider: 'himalayas', board: 'microsoft' },
  { id: 'adobe', name: 'Adobe', initials: 'A', color: '#f6a7aa', industry: '디자인 · 크리에이티브', careerUrl: 'https://careers.adobe.com/us/en', provider: 'himalayas', board: 'adobe' },
  { id: 'salesforce', name: 'Salesforce', initials: 'S', color: '#8cc9fa', industry: '클라우드 · 기업용 소프트웨어', careerUrl: 'https://www.salesforce.com/company/careers/', provider: 'himalayas', board: 'salesforce' },
  { id: 'cisco', name: 'Cisco', initials: 'C', color: '#83d1c7', industry: '네트워크 · 보안', careerUrl: 'https://careers.cisco.com/global/en', provider: 'himalayas', board: 'cisco' },
  { id: 'qualcomm', name: 'Qualcomm', initials: 'Q', color: '#a4a3ff', industry: '반도체 · 무선 통신', careerUrl: 'https://careers.qualcomm.com/careers', provider: 'himalayas', board: 'qualcomm' },
  { id: 'broadcom', name: 'Broadcom', initials: 'B', color: '#f5a193', industry: '반도체 · 인프라 소프트웨어', careerUrl: 'https://www.broadcom.com/company/careers', provider: 'himalayas', board: 'broadcom' },
  { id: 'redhat', name: 'Red Hat', initials: 'RH', color: '#ff929b', industry: '오픈소스 · 클라우드', careerUrl: 'https://www.redhat.com/en/jobs', provider: 'himalayas', board: 'red-hat' },
]
