// Country/area identifiers, independent of the cities drawn on the map.
// UN M49 snapshot, 2026-09-20: https://unstats.un.org/unsd/methodology/m49/overview/
// TW and the user-assigned XK use Unicode CLDR code mappings; XK is not an ISO assignment.
// Geographic groups serve the current map filters, not employment eligibility.
// [alpha-2, alpha-3, map region (null when no corresponding tab), reference name]
export const COUNTRY_DATA = [
  ["AD", "AND", "europe", "Andorra"],
  ["AE", "ARE", "asia-pacific", "United Arab Emirates"],
  ["AF", "AFG", "asia-pacific", "Afghanistan"],
  ["AG", "ATG", "americas", "Antigua and Barbuda"],
  ["AI", "AIA", "americas", "Anguilla"],
  ["AL", "ALB", "europe", "Albania"],
  ["AM", "ARM", "asia-pacific", "Armenia"],
  ["AO", "AGO", null, "Angola"],
  ["AQ", "ATA", null, "Antarctica"],
  ["AR", "ARG", "americas", "Argentina"],
  ["AS", "ASM", "asia-pacific", "American Samoa"],
  ["AT", "AUT", "europe", "Austria"],
  ["AU", "AUS", "asia-pacific", "Australia"],
  ["AW", "ABW", "americas", "Aruba"],
  ["AX", "ALA", "europe", "Åland Islands"],
  ["AZ", "AZE", "asia-pacific", "Azerbaijan"],
  ["BA", "BIH", "europe", "Bosnia and Herzegovina"],
  ["BB", "BRB", "americas", "Barbados"],
  ["BD", "BGD", "asia-pacific", "Bangladesh"],
  ["BE", "BEL", "europe", "Belgium"],
  ["BF", "BFA", null, "Burkina Faso"],
  ["BG", "BGR", "europe", "Bulgaria"],
  ["BH", "BHR", "asia-pacific", "Bahrain"],
  ["BI", "BDI", null, "Burundi"],
  ["BJ", "BEN", null, "Benin"],
  ["BL", "BLM", "americas", "Saint Barthélemy"],
  ["BM", "BMU", "americas", "Bermuda"],
  ["BN", "BRN", "asia-pacific", "Brunei Darussalam"],
  ["BO", "BOL", "americas", "Bolivia (Plurinational State of)"],
  ["BQ", "BES", "americas", "Bonaire, Sint Eustatius and Saba"],
  ["BR", "BRA", "americas", "Brazil"],
  ["BS", "BHS", "americas", "Bahamas"],
  ["BT", "BTN", "asia-pacific", "Bhutan"],
  ["BV", "BVT", "americas", "Bouvet Island"],
  ["BW", "BWA", null, "Botswana"],
  ["BY", "BLR", "europe", "Belarus"],
  ["BZ", "BLZ", "americas", "Belize"],
  ["CA", "CAN", "americas", "Canada"],
  ["CC", "CCK", "asia-pacific", "Cocos (Keeling) Islands"],
  ["CD", "COD", null, "Democratic Republic of the Congo"],
  ["CF", "CAF", null, "Central African Republic"],
  ["CG", "COG", null, "Congo"],
  ["CH", "CHE", "europe", "Switzerland"],
  ["CI", "CIV", null, "Côte d’Ivoire"],
  ["CK", "COK", "asia-pacific", "Cook Islands"],
  ["CL", "CHL", "americas", "Chile"],
  ["CM", "CMR", null, "Cameroon"],
  ["CN", "CHN", "asia-pacific", "China"],
  ["CO", "COL", "americas", "Colombia"],
  ["CR", "CRI", "americas", "Costa Rica"],
  ["CU", "CUB", "americas", "Cuba"],
  ["CV", "CPV", null, "Cabo Verde"],
  ["CW", "CUW", "americas", "Curaçao"],
  ["CX", "CXR", "asia-pacific", "Christmas Island"],
  ["CY", "CYP", "asia-pacific", "Cyprus"],
  ["CZ", "CZE", "europe", "Czechia"],
  ["DE", "DEU", "europe", "Germany"],
  ["DJ", "DJI", null, "Djibouti"],
  ["DK", "DNK", "europe", "Denmark"],
  ["DM", "DMA", "americas", "Dominica"],
  ["DO", "DOM", "americas", "Dominican Republic"],
  ["DZ", "DZA", null, "Algeria"],
  ["EC", "ECU", "americas", "Ecuador"],
  ["EE", "EST", "europe", "Estonia"],
  ["EG", "EGY", null, "Egypt"],
  ["EH", "ESH", null, "Western Sahara"],
  ["ER", "ERI", null, "Eritrea"],
  ["ES", "ESP", "europe", "Spain"],
  ["ET", "ETH", null, "Ethiopia"],
  ["FI", "FIN", "europe", "Finland"],
  ["FJ", "FJI", "asia-pacific", "Fiji"],
  ["FK", "FLK", "americas", "Falkland Islands (Malvinas)"],
  ["FM", "FSM", "asia-pacific", "Micronesia (Federated States of)"],
  ["FO", "FRO", "europe", "Faroe Islands"],
  ["FR", "FRA", "europe", "France"],
  ["GA", "GAB", null, "Gabon"],
  ["GB", "GBR", "europe", "United Kingdom of Great Britain and Northern Ireland"],
  ["GD", "GRD", "americas", "Grenada"],
  ["GE", "GEO", "asia-pacific", "Georgia"],
  ["GF", "GUF", "americas", "French Guiana"],
  ["GG", "GGY", "europe", "Guernsey"],
  ["GH", "GHA", null, "Ghana"],
  ["GI", "GIB", "europe", "Gibraltar"],
  ["GL", "GRL", "americas", "Greenland"],
  ["GM", "GMB", null, "Gambia"],
  ["GN", "GIN", null, "Guinea"],
  ["GP", "GLP", "americas", "Guadeloupe"],
  ["GQ", "GNQ", null, "Equatorial Guinea"],
  ["GR", "GRC", "europe", "Greece"],
  ["GS", "SGS", "americas", "South Georgia and the South Sandwich Islands"],
  ["GT", "GTM", "americas", "Guatemala"],
  ["GU", "GUM", "asia-pacific", "Guam"],
  ["GW", "GNB", null, "Guinea-Bissau"],
  ["GY", "GUY", "americas", "Guyana"],
  ["HK", "HKG", "asia-pacific", "China, Hong Kong Special Administrative Region"],
  ["HM", "HMD", "asia-pacific", "Heard Island and McDonald Islands"],
  ["HN", "HND", "americas", "Honduras"],
  ["HR", "HRV", "europe", "Croatia"],
  ["HT", "HTI", "americas", "Haiti"],
  ["HU", "HUN", "europe", "Hungary"],
  ["ID", "IDN", "asia-pacific", "Indonesia"],
  ["IE", "IRL", "europe", "Ireland"],
  ["IL", "ISR", "asia-pacific", "Israel"],
  ["IM", "IMN", "europe", "Isle of Man"],
  ["IN", "IND", "asia-pacific", "India"],
  ["IO", "IOT", null, "British Indian Ocean Territory"],
  ["IQ", "IRQ", "asia-pacific", "Iraq"],
  ["IR", "IRN", "asia-pacific", "Iran (Islamic Republic of)"],
  ["IS", "ISL", "europe", "Iceland"],
  ["IT", "ITA", "europe", "Italy"],
  ["JE", "JEY", "europe", "Jersey"],
  ["JM", "JAM", "americas", "Jamaica"],
  ["JO", "JOR", "asia-pacific", "Jordan"],
  ["JP", "JPN", "asia-pacific", "Japan"],
  ["KE", "KEN", null, "Kenya"],
  ["KG", "KGZ", "asia-pacific", "Kyrgyzstan"],
  ["KH", "KHM", "asia-pacific", "Cambodia"],
  ["KI", "KIR", "asia-pacific", "Kiribati"],
  ["KM", "COM", null, "Comoros"],
  ["KN", "KNA", "americas", "Saint Kitts and Nevis"],
  ["KP", "PRK", "asia-pacific", "Democratic People's Republic of Korea"],
  ["KR", "KOR", "asia-pacific", "Republic of Korea"],
  ["KW", "KWT", "asia-pacific", "Kuwait"],
  ["KY", "CYM", "americas", "Cayman Islands"],
  ["KZ", "KAZ", "asia-pacific", "Kazakhstan"],
  ["LA", "LAO", "asia-pacific", "Lao People's Democratic Republic"],
  ["LB", "LBN", "asia-pacific", "Lebanon"],
  ["LC", "LCA", "americas", "Saint Lucia"],
  ["LI", "LIE", "europe", "Liechtenstein"],
  ["LK", "LKA", "asia-pacific", "Sri Lanka"],
  ["LR", "LBR", null, "Liberia"],
  ["LS", "LSO", null, "Lesotho"],
  ["LT", "LTU", "europe", "Lithuania"],
  ["LU", "LUX", "europe", "Luxembourg"],
  ["LV", "LVA", "europe", "Latvia"],
  ["LY", "LBY", null, "Libya"],
  ["MA", "MAR", null, "Morocco"],
  ["MC", "MCO", "europe", "Monaco"],
  ["MD", "MDA", "europe", "Republic of Moldova"],
  ["ME", "MNE", "europe", "Montenegro"],
  ["MF", "MAF", "americas", "Saint Martin (French Part)"],
  ["MG", "MDG", null, "Madagascar"],
  ["MH", "MHL", "asia-pacific", "Marshall Islands"],
  ["MK", "MKD", "europe", "North Macedonia"],
  ["ML", "MLI", null, "Mali"],
  ["MM", "MMR", "asia-pacific", "Myanmar"],
  ["MN", "MNG", "asia-pacific", "Mongolia"],
  ["MO", "MAC", "asia-pacific", "China, Macao Special Administrative Region"],
  ["MP", "MNP", "asia-pacific", "Northern Mariana Islands"],
  ["MQ", "MTQ", "americas", "Martinique"],
  ["MR", "MRT", null, "Mauritania"],
  ["MS", "MSR", "americas", "Montserrat"],
  ["MT", "MLT", "europe", "Malta"],
  ["MU", "MUS", null, "Mauritius"],
  ["MV", "MDV", "asia-pacific", "Maldives"],
  ["MW", "MWI", null, "Malawi"],
  ["MX", "MEX", "americas", "Mexico"],
  ["MY", "MYS", "asia-pacific", "Malaysia"],
  ["MZ", "MOZ", null, "Mozambique"],
  ["NA", "NAM", null, "Namibia"],
  ["NC", "NCL", "asia-pacific", "New Caledonia"],
  ["NE", "NER", null, "Niger"],
  ["NF", "NFK", "asia-pacific", "Norfolk Island"],
  ["NG", "NGA", null, "Nigeria"],
  ["NI", "NIC", "americas", "Nicaragua"],
  ["NL", "NLD", "europe", "Netherlands (Kingdom of the)"],
  ["NO", "NOR", "europe", "Norway"],
  ["NP", "NPL", "asia-pacific", "Nepal"],
  ["NR", "NRU", "asia-pacific", "Naoero"],
  ["NU", "NIU", "asia-pacific", "Niue"],
  ["NZ", "NZL", "asia-pacific", "New Zealand"],
  ["OM", "OMN", "asia-pacific", "Oman"],
  ["PA", "PAN", "americas", "Panama"],
  ["PE", "PER", "americas", "Peru"],
  ["PF", "PYF", "asia-pacific", "French Polynesia"],
  ["PG", "PNG", "asia-pacific", "Papua New Guinea"],
  ["PH", "PHL", "asia-pacific", "Philippines"],
  ["PK", "PAK", "asia-pacific", "Pakistan"],
  ["PL", "POL", "europe", "Poland"],
  ["PM", "SPM", "americas", "Saint Pierre and Miquelon"],
  ["PN", "PCN", "asia-pacific", "Pitcairn"],
  ["PR", "PRI", "americas", "Puerto Rico"],
  ["PS", "PSE", "asia-pacific", "State of Palestine"],
  ["PT", "PRT", "europe", "Portugal"],
  ["PW", "PLW", "asia-pacific", "Palau"],
  ["PY", "PRY", "americas", "Paraguay"],
  ["QA", "QAT", "asia-pacific", "Qatar"],
  ["RE", "REU", null, "Réunion"],
  ["RO", "ROU", "europe", "Romania"],
  ["RS", "SRB", "europe", "Serbia"],
  ["RU", "RUS", "europe", "Russian Federation"],
  ["RW", "RWA", null, "Rwanda"],
  ["SA", "SAU", "asia-pacific", "Saudi Arabia"],
  ["SB", "SLB", "asia-pacific", "Solomon Islands"],
  ["SC", "SYC", null, "Seychelles"],
  ["SD", "SDN", null, "Sudan"],
  ["SE", "SWE", "europe", "Sweden"],
  ["SG", "SGP", "asia-pacific", "Singapore"],
  ["SH", "SHN", null, "Saint Helena"],
  ["SI", "SVN", "europe", "Slovenia"],
  ["SJ", "SJM", "europe", "Svalbard and Jan Mayen Islands"],
  ["SK", "SVK", "europe", "Slovakia"],
  ["SL", "SLE", null, "Sierra Leone"],
  ["SM", "SMR", "europe", "San Marino"],
  ["SN", "SEN", null, "Senegal"],
  ["SO", "SOM", null, "Somalia"],
  ["SR", "SUR", "americas", "Suriname"],
  ["SS", "SSD", null, "South Sudan"],
  ["ST", "STP", null, "Sao Tome and Principe"],
  ["SV", "SLV", "americas", "El Salvador"],
  ["SX", "SXM", "americas", "Sint Maarten (Dutch part)"],
  ["SY", "SYR", "asia-pacific", "Syrian Arab Republic"],
  ["SZ", "SWZ", null, "Eswatini"],
  ["TC", "TCA", "americas", "Turks and Caicos Islands"],
  ["TD", "TCD", null, "Chad"],
  ["TF", "ATF", null, "French Southern Territories"],
  ["TG", "TGO", null, "Togo"],
  ["TH", "THA", "asia-pacific", "Thailand"],
  ["TJ", "TJK", "asia-pacific", "Tajikistan"],
  ["TK", "TKL", "asia-pacific", "Tokelau"],
  ["TL", "TLS", "asia-pacific", "Timor-Leste"],
  ["TM", "TKM", "asia-pacific", "Turkmenistan"],
  ["TN", "TUN", null, "Tunisia"],
  ["TO", "TON", "asia-pacific", "Tonga"],
  ["TR", "TUR", "asia-pacific", "Türkiye"],
  ["TT", "TTO", "americas", "Trinidad and Tobago"],
  ["TV", "TUV", "asia-pacific", "Tuvalu"],
  ["TW", "TWN", "asia-pacific", "Taiwan"],
  ["TZ", "TZA", null, "United Republic of Tanzania"],
  ["UA", "UKR", "europe", "Ukraine"],
  ["UG", "UGA", null, "Uganda"],
  ["UM", "UMI", "asia-pacific", "United States Minor Outlying Islands"],
  ["US", "USA", "americas", "United States of America"],
  ["UY", "URY", "americas", "Uruguay"],
  ["UZ", "UZB", "asia-pacific", "Uzbekistan"],
  ["VA", "VAT", "europe", "Holy See"],
  ["VC", "VCT", "americas", "Saint Vincent and the Grenadines"],
  ["VE", "VEN", "americas", "Venezuela (Bolivarian Republic of)"],
  ["VG", "VGB", "americas", "British Virgin Islands"],
  ["VI", "VIR", "americas", "United States Virgin Islands"],
  ["VN", "VNM", "asia-pacific", "Viet Nam"],
  ["VU", "VUT", "asia-pacific", "Vanuatu"],
  ["WF", "WLF", "asia-pacific", "Wallis and Futuna Islands"],
  ["WS", "WSM", "asia-pacific", "Samoa"],
  ["XK", "XKK", "europe", "Kosovo"],
  ["YE", "YEM", "asia-pacific", "Yemen"],
  ["YT", "MYT", null, "Mayotte"],
  ["ZA", "ZAF", null, "South Africa"],
  ["ZM", "ZMB", null, "Zambia"],
  ["ZW", "ZWE", null, "Zimbabwe"],
] as const
